# NLP Preprocessing & Feature Engineering

In [1]:
#pip install nltk

In [2]:
import pandas as pd
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...

True

In [3]:
data={'Review':['I absolutely love this mobile phone!','The battery life is very poor.',
                'Amazing camera and excellent performance.',
                'Worst product I have ever purchased.',
                'Value for money. Highly recommended!']}
df=pd.DataFrame(data)
df

                                      Review
0       I absolutely love this mobile phone!
1             The battery life is very poor.
2  Amazing camera and excellent performance.
3       Worst product I have ever purchased.
4       Value for money. Highly recommended!

In [4]:
df['lower']=df['Review'].str.lower()
df

,Review,lower
0,I absolutely love this mobile phone!,i absolutely love this mobile phone!
1,The battery life is very poor.,the battery life is very poor.
2,Amazing camera and excellent performance.,amazing camera and excellent performance.
3,Worst product I have ever purchased.,worst product i have ever purchased.
4,Value for money. Highly recommended!,value for money. highly recommended!

In [8]:
import string

In [13]:
df['no_punctuation']=df['lower'].apply(

    lambda x:x.translate(

        str.maketrans('','',string.punctuation)
    )
)
df

,Review,lower,no_punctuaion,no_punctuation
0,I absolutely love this mobile phone!,i absolutely love this mobile phone!,i absolutely love this mobile phone,i absolutely love this mobile phone
1,The battery life is very poor.,the battery life is very poor.,the battery life is very poor,the battery life is very poor
2,Amazing camera and excellent performance.,amazing camera and excellent performance.,amazing camera and excellent performance,amazing camera and excellent performance
3,Worst product I have ever purchased.,worst product i have ever purchased.,worst product i have ever purchased,worst product i have ever purchased
4,Value for money. Highly recommended!,value for money. highly recommended!,value for money highly recommended,value for money highly recommended

In [14]:
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [17]:
from nltk.tokenize import word_tokenize
df['tokens']=df['no_punctuation'].apply(word_tokenize)
df

,Review,lower,no_punctuaion,no_punctuation,tokenize,tokens
0,I absolutely love this mobile phone!,i absolutely love this mobile phone!,i absolutely love this mobile phone,i absolutely love this mobile phone,"[i, absolutely, love, this, mobile, phone]","[i, absolutely, love, this, mobile, phone]"
1,The battery life is very poor.,the battery life is very poor.,the battery life is very poor,the battery life is very poor,"[the, battery, life, is, very, poor]","[the, battery, life, is, very, poor]"
2,Amazing camera and excellent performance.,amazing camera and excellent performance.,amazing camera and excellent performance,amazing camera and excellent performance,"[amazing, camera, and, excellent, performance]","[amazing, camera, and, excellent, performance]"
3,Worst product I have ever purchased.,worst product i have ever purchased.,worst product i have ever purchased,worst product i have ever purchased,"[worst, product, i, have, ever, purchased]","[worst, product, i, have, ever, purchased]"
4,Value for money. Highly recommended!,value for money. highly recommended!,value for money highly recommended,value for money highly recommended,"[value, for, money, highly, recommended]","[value, for, money, highly, recommended]"

In [18]:
from nltk.corpus import stopwords
stop_words=set(stopwords.words('english'))
df['filtered_tokens']=df['tokens'].apply(lambda x:[w for w in x if w not in stop_words])
df

,Review,lower,no_punctuaion,no_punctuation,tokenize,tokens,filtered_tokens
0,I absolutely love this mobile phone!,i absolutely love this mobile phone!,i absolutely love this mobile phone,i absolutely love this mobile phone,"[i, absolutely, love, this, mobile, phone]","[i, absolutely, love, this, mobile, phone]","[absolutely, love, mobile, phone]"
1,The battery life is very poor.,the battery life is very poor.,the battery life is very poor,the battery life is very poor,"[the, battery, life, is, very, poor]","[the, battery, life, is, very, poor]","[battery, life, poor]"
2,Amazing camera and excellent performance.,amazing camera and excellent performance.,amazing camera and excellent performance,amazing camera and excellent performance,"[amazing, camera, and, excellent, performance]","[amazing, camera, and, excellent, performance]","[amazing, camera, excellent, performance]"
3,Worst product I have ever purchased.,worst product i have ever purchased.,worst product i have ever purchased,worst product i have ever purchased,"[worst, product, i, have, ever, purchased]","[worst, product, i, have, ever, purchased]","[worst, product, ever, purchased]"
4,Value for money. Highly recommended!,value for money. highly recommended!,value for money highly recommended,value for money highly recommended,"[value, for, money, highly, recommended]","[value, for, money, highly, recommended]","[value, money, highly, recommended]"

In [19]:
from nltk.stem import PorterStemmer
stemmer=PorterStemmer()
df['stemmed']=df['filtered_tokens'].apply(lambda x : [stemmer.stem(w) for w in x])
df

,Review,lower,no_punctuaion,no_punctuation,tokenize,tokens,filtered_tokens,stemmed
0,I absolutely love this mobile phone!,i absolutely love this mobile phone!,i absolutely love this mobile phone,i absolutely love this mobile phone,"[i, absolutely, love, this, mobile, phone]","[i, absolutely, love, this, mobile, phone]","[absolutely, love, mobile, phone]","[absolut, love, mobil, phone]"
1,The battery life is very poor.,the battery life is very poor.,the battery life is very poor,the battery life is very poor,"[the, battery, life, is, very, poor]","[the, battery, life, is, very, poor]","[battery, life, poor]","[batteri, life, poor]"
2,Amazing camera and excellent performance.,amazing camera and excellent performance.,amazing camera and excellent performance,amazing camera and excellent performance,"[amazing, camera, and, excellent, performance]","[amazing, camera, and, excellent, performance]","[amazing, camera, excellent, performance]","[amaz, camera, excel, perform]"
3,Worst product I have ever purchased.,worst product i have ever purchased.,worst product i have ever purchased,worst product i have ever purchased,"[worst, product, i, have, ever, purchased]","[worst, product, i, have, ever, purchased]","[worst, product, ever, purchased]","[worst, product, ever, purchas]"
4,Value for money. Highly recommended!,value for money. highly recommended!,value for money highly recommended,value for money highly recommended,"[value, for, money, highly, recommended]","[value, for, money, highly, recommended]","[value, money, highly, recommended]","[valu, money, highli, recommend]"

In [21]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
df['lemmatized']=df['filtered_tokens'].apply(lambda x :[lemmatizer.lemmatize(w) for w in x])
df['clean_text']=df['lemmatized'].apply(lambda x:' '.join(x))
df

,Review,lower,no_punctuaion,no_punctuation,tokenize,tokens,filtered_tokens,stemmed,lemmatized,clean_text
0,I absolutely love this mobile phone!,i absolutely love this mobile phone!,i absolutely love this mobile phone,i absolutely love this mobile phone,"[i, absolutely, love, this, mobile, phone]","[i, absolutely, love, this, mobile, phone]","[absolutely, love, mobile, phone]","[absolut, love, mobil, phone]","[absolutely, love, mobile, phone]",absolutely love mobile phone
1,The battery life is very poor.,the battery life is very poor.,the battery life is very poor,the battery life is very poor,"[the, battery, life, is, very, poor]","[the, battery, life, is, very, poor]","[battery, life, poor]","[batteri, life, poor]","[battery, life, poor]",battery life poor
2,Amazing camera and excellent performance.,amazing camera and excellent performance.,amazing camera and excellent performance,amazing camera and excellent performance,"[amazing, camera, and, excellent, performance]","[amazing, camera, and, excellent, performance]","[amazing, camera, excellent, performance]","[amaz, camera, excel, perform]","[amazing, camera, excellent, performance]",amazing camera excellent performance
3,Worst product I have ever purchased.,worst product i have ever purchased.,worst product i have ever purchased,worst product i have ever purchased,"[worst, product, i, have, ever, purchased]","[worst, product, i, have, ever, purchased]","[worst, product, ever, purchased]","[worst, product, ever, purchas]","[worst, product, ever, purchased]",worst product ever purchased
4,Value for money. Highly recommended!,value for money. highly recommended!,value for money highly recommended,value for money highly recommended,"[value, for, money, highly, recommended]","[value, for, money, highly, recommended]","[value, money, highly, recommended]","[valu, money, highli, recommend]","[value, money, highly, recommended]",value money highly recommended

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
bow=cv.fit_transform(df['clean_text'])
import pandas as pd
pd.DataFrame(bow.toarray(),columns=cv.get_feature_names_out())

,absolutely,amazing,battery,camera,ever,excellent,highly,life,love,mobile,money,performance,phone,poor,product,purchased,recommended,value,worst
0,1,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0
1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0
2,0,1,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,1
4,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,1,0

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X=tfidf.fit_transform(df['clean_text'])
pd.DataFrame(X.toarray(),columns=tfidf.get_feature_names_out()).round(3)

,absolutely,amazing,battery,camera,ever,excellent,highly,life,love,mobile,money,performance,phone,poor,product,purchased,recommended,value,worst
0,0.5,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.5,0.5,0.0,0.0,0.5,0.000,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.577,0.0,0.0,0.0,0.0,0.577,0.0,0.0,0.0,0.0,0.0,0.577,0.0,0.0,0.0,0.0,0.0
2,0.0,0.5,0.000,0.5,0.0,0.5,0.0,0.000,0.0,0.0,0.0,0.5,0.0,0.000,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.000,0.0,0.5,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.5,0.5,0.0,0.0,0.5
4,0.0,0.0,0.000,0.0,0.0,0.0,0.5,0.000,0.0,0.0,0.5,0.0,0.0,0.000,0.0,0.0,0.5,0.5,0.0